///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsInterBold = 'assets/fonts/Inter-Bold.otf';
  static const String fontsInterMedium = 'assets/fonts/Inter-Medium.otf';
  static const String fontsInterRegular = 'assets/fonts/Inter-Regular.otf';
  static const String fontsInterSemiBold = 'assets/fonts/Inter-SemiBold.otf';
  static const String imagesAmericanExpress = 'assets/images/americanExpress.png';
  static const String imagesAppEmblem = 'assets/images/appEmblem.svg';
  static const String imagesAppLogo = 'assets/images/appLogo.svg';
  static const String imagesAppleLogo = 'assets/images/appleLogo.svg';
  static const String imagesAppointCall = 'assets/images/appointCall.png';
  static const String imagesAppointInPerson = 'assets/images/appointInPerson.png';
  static const String imagesAppointTypeIcon = 'assets/images/appointTypeIcon.png';
  static const String imagesAppointVideoCall = 'assets/images/appointVideoCall.png';
  static const String imagesBaby = 'assets/images/baby.png';
  static const String imagesBarclays = 'assets/images/barclays.png';
  static const String imagesBookingConfirmed = 'assets/images/bookingConfirmed.svg';
  static const String imagesBrain = 'assets/images/brain.png';
  static const String imagesCalendarIcon = 'assets/images/calendarIcon.svg';
  static const String imagesCalendarIconActive = 'assets/images/calendarIconActive.svg';
  static const String imagesCalenderBookingIcon = 'assets/images/calenderBookingIcon.png';
  static const String imagesCapitalOne = 'assets/images/capitalOne.png';
  static const String imagesCardiology = 'assets/images/Cardiology.png';
  static const String imagesDefaultAvatar = 'assets/images/defaultAvatar.png';
  static const String imagesDermatology = 'assets/images/dermatology.png';
  static const String imagesDoctor = 'assets/images/doctor.png';
  static const String imagesDoctorVector = 'assets/images/doctor_vector.png';
  static const String imagesFacebookLogo = 'assets/images/facebookLogo.svg';
  static const String imagesGastrenterology = 'assets/images/gastrenterology.png';
  static const String imagesGoogleLogo = 'assets/images/googleLogo.svg';
  static const String imagesGynecology = 'assets/images/gynecology.png';
  static const String imagesHomeIcon = 'assets/images/homeIcon.svg';
  static const String imagesHomeIconActive = 'assets/images/homeIconActive.svg';
  static const String imagesHomePageBlueContainerPattern = 'assets/images/homePageBlueContainerPattern.png';
  static const String imagesKidneys = 'assets/images/kidneys.png';
  static const String imagesLinearEffect = 'assets/images/linearEffect.png';
  static const String imagesMap = 'assets/images/map.png';
  static const String imagesMastercard = 'assets/images/mastercard.png';
  static const String imagesMessageIcon = 'assets/images/messageIcon.svg';
  static const String imagesMessageIconActive = 'assets/images/messageIconActive.svg';
  static const String imagesNotificationIcon = 'assets/images/notificationIcon.svg';
  static const String imagesNurse = 'assets/images/nurse.png';
  static const String imagesOphthalmology = 'assets/images/ophthalmology.png';
  static const String imagesOrthopedics = 'assets/images/orthopedics.png';
  static const String imagesPaypal = 'assets/images/paypal.png';
  static const String imagesProfAvatar = 'assets/images/profAvatar.png';
  static const String imagesPsychiatry = 'assets/images/psychiatry.png';
  static const String imagesRandy = 'assets/images/randy.png';
  static const String imagesSearchIcon = 'assets/images/searchIcon.svg';
  static const String imagesSortIcon = 'assets/images/sortIcon.svg';
  static const String utilsAssets = 'lib/core/utils/assets.dart';

}
